import logging
logger = logging.getLogger(__name__)

import typing
if typing.TYPE_CHECKING:
    import telegram

import json
import os
import urllib.parse

from telegram import constants

from .llm_api import complete
from .throttle import Throttle
from datetime import datetime, timedelta

MAX_INPUT_LENGTH = int(os.getenv('MAX_INPUT_LENGTH', '2000'))

throttle = Throttle()

_prompt_template: str | None = None

def _load_prompt_template() -> str:
  global _prompt_template
  if _prompt_template is None:
    with open('prompt_template.txt', 'r') as f:
      _prompt_template = f.read()
  return _prompt_template

def parse_duration(duration_str: str) -> timedelta:
  days, hours, minutes = 0, 0, 0
  current_num = ''
  for char in duration_str:
    if char.isdigit():
      current_num += char
    else:
      if char == 'd':
        days = int(current_num) if current_num else 0
      elif char == 'h':
        hours = int(current_num) if current_num else 0
      elif char == 'm':
        minutes = int(current_num) if current_num else 0
      current_num = ''
  return timedelta(days=days, hours=hours, minutes=minutes)

async def handle_general_message(update: 'telegram.Update', context: 'telegram.ext.CallbackContext') -> None:
  await throttle.call()
  replyMessage = await update.message.reply_text('Processing...')
  content = ''
  if update.message.reply_to_message:
    content += update.message.reply_to_message.text or ''
  content += update.message.text or update.message.caption or ''
  content = content[:MAX_INPUT_LENGTH]
  logger.info(f'Processing: <{content}>')
  if not content.strip():
    logger.error('Empty input. Task aborted.')
    await replyMessage.edit_text('ERROR: No input. Task aborted.')
    return
  now = datetime.now()
  prompt = _load_prompt_template().format(**{
    'content': content,
    'now': now.isoformat(timespec='seconds') + ' ' + now.strftime('%A'),
  })
  message = ''
  result = []
  try:
    async for token in complete(prompt):
      result.append(token)
  except Exception as e:
    logger.error(f'ERROR: {repr(e)}')
    message += ''.join(result) + '\nERROR: LLM API request failed: ' + repr(e)
  if len(result) == 0 and not message:
    logger.error('No result returned.')
    message += 'ERROR: No result returned.\n'
  else:
    json_result_str = ''.join(result)
    # Strip any surrounding prose — keep only the JSON object
    start = json_result_str.find('{')
    end = json_result_str.rfind('}') + 1
    if start != -1 and end > start:
      json_result_str = json_result_str[start:end]
    message += json_result_str
    try:
      json_result = json.loads(json_result_str)
      logger.info(f'Result: {json_result}')
      start_time = datetime.fromisoformat(json_result['start'])
      duration = parse_duration(json_result['duration'])
      end_time = start_time + duration
      dates_param = f"{start_time.strftime('%Y%m%dT%H%M%S')}Z/{end_time.strftime('%Y%m%dT%H%M%S')}Z"
      message += '\n' + 'https://www.google.com/calendar/render?action=TEMPLATE' \
        + '&text=' + urllib.parse.quote(json_result['text']) \
        + '&dates=' + dates_param \
        + '&details=' + urllib.parse.quote(content[:200] + '\n\n' + 'generated by llm') \
        + '&location=' + urllib.parse.quote(json_result.get('location', '')) \
        + '&sf=true&output=xml'
      logger.info(f'Message: {message}')
    except (json.JSONDecodeError, KeyError, ValueError) as e:
      logger.error(f'Failed to parse LLM response: {repr(e)}')
      message += f'\nERROR: Failed to parse result: {repr(e)}'
  await replyMessage.edit_text(message)
